const companyNames = [
    "ABC Corporation",
    "XYZ Industries",
    "Smith & Co.",
    "Johnson Enterprises",
    "Global Tech Solutions",
    "Pacific Foods",
    "Sunset Marketing",
    "Zenith Group",
    "Evergreen Technologies",
    "Pinnacle Logistics",
    "Harmony Healthcare",
    "Silver Star Finance",
    "Elite Construction",
    "Nova Pharmaceuticals",
    "Summit Consulting",
    "Oceanic Shipping",
    "Apex Software",
    "Golden Gate Investments",
    "Emerald Energy",
    "Vista Media",
    "Alpha Bank",
    "Prime Realty",
    "Sapphire Inc.",
    "Crystal Clear Services",
    "Titan Motors",
    "Phoenix Law Firm",
    "Eagle Aviation",
    "Diamond Design",
    "Harbor Hotels",
    "Liberty Legal",
    "Rainbow Retail",
    "Polaris Productions",
    "Meridian Manufacturing",
    "Trinity Transport",
    "Starlight Studios",
    "Sequoia Solutions",
    "Aspen Architecture",
    "Crimson Consulting",
    "Bluebird Biotech",
    "Horizon Healthcare",
    "Silver Fox Security",
    "Summit Software",
    "Ocean View Resorts",
    "Titanium Tech",
    "Zenith Zephyr",
    "Evergreen Estates",
    "Pinnacle Properties",
    "Harmony Hotels"
]
const jobTitles = [
    "CEO",
    "COO",
    "CFO",
    "CTO",
    "VP of Sales",
    "VP of Marketing",
    "VP of Operations",
    "Chief Legal Officer",
    "Chief Compliance Officer",
    "Chief Technology Officer",
    "Chief Financial Officer",
    "Director of Human Resources",
    "Director of Sales",
    "Director of Marketing",
    "Director of Operations",
    "Senior Manager",
    "Manager",
    "Assistant Manager",
    "Project Manager",
    "Team Lead",
    "Software Engineer",
    "Marketing Specialist",
    "Sales Representative",
    "Accountant",
    "Financial Analyst",
    "Customer Service Representative",
    "Legal Counsel",
    "HR Coordinator",
    "Administrative Assistant",
    "Executive Assistant",
    "Research Scientist",
    "Product Manager",
    "Operations Analyst",
    "Business Development Manager",
    "Consultant",
    "Designer",
    "Architect",
    "Engineer",
    "Technician",
    "Analyst",
    "Supervisor",
    "Trainer",
    "Specialist",
    "Advisor",
    "Coordinator",
    "Associate"
]
const departments = [
    "Sales",
    "Marketing",
    "Finance",
    "Operations",
    "Human Resources",
    "Legal",
    "Information Technology",
    "Customer Service",
    "Research and Development",
    "Product Development",
    "Engineering",
    "Design",
    "Accounting",
    "Administration",
    "Purchasing",
    "Logistics",
    "Quality Assurance",
    "Training",
    "Business Development",
    "Consulting",
    "Support",
    "Public Relations",
    "Security",
    "Compliance",
    "Strategy",
    "Project Management",
    "Maintenance",
    "Production",
    "Inventory Control",
    "Facilities Management"
]
const companyLocations = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Houston, TX",
    "Phoenix, AZ",
    "Philadelphia, PA",
    "San Antonio, TX",
    "San Diego, CA",
    "Dallas, TX",
    "San Jose, CA",
    "Austin, TX",
    "Jacksonville, FL",
    "Fort Worth, TX",
    "Columbus, OH",
    "San Francisco, CA",
    "Charlotte, NC",
    "Indianapolis, IN",
    "Seattle, WA",
    "Denver, CO",
    "Washington, DC",
    "Boston, MA",
    "El Paso, TX",
    "Detroit, MI",
    "Nashville, TN",
    "Portland, OR",
    "Memphis, TN",
    "Oklahoma City, OK",
    "Las Vegas, NV",
    "Louisville, KY",
    "Baltimore, MD",
    "Milwaukee, WI",
    "Albuquerque, NM",
    "Tucson, AZ",
    "Fresno, CA",
    "Sacramento, CA",
    "Mesa, AZ",
    "Kansas City, MO",
    "Atlanta, GA",
    "Long Beach, CA",
    "Omaha, NE",
    "Raleigh, NC",
    "Colorado Springs, CO",
    "Miami, FL",
    "Oakland, CA",
    "Minneapolis, MN",
    "Tulsa, OK",
    "Wichita, KS",
    "New Orleans, LA"
]  


/**
 * Generates a random company information based on the specified type.
 * @param type - The type of company information to generate. Can be 'name', 'job', 'department', 'location', or 'json'.
 * @returns The generated company information based on the specified type.
 */
export default function generateCompany(type: 'name' | 'job' | 'department' | 'location' | 'json') {

    const name = companyNames[Math.floor(Math.random() * companyNames.length)]
    const job = jobTitles[Math.floor(Math.random() * jobTitles.length)]
    const department = departments[Math.floor(Math.random() * departments.length)]
    const location = companyLocations[Math.floor(Math.random() * companyLocations.length)]
  
    if (type === 'name') {
        return name
    } else if (type === 'job') {
        return job
    } else if (type === 'department') {
        return department
    } else if (type === 'location') {
        return location
    } else if (type === 'json') {
        return {
            name,
            job,
            department,
            location
        }
    }
}