name: Update Package Version

on:
  release:
    types: [published]
  
permissions: write-all
  
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Update version from git tag
      id: update_version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        if [[ $TAG_NAME == *"-beta"* ]]; then
          npm version $TAG_NAME --preid rc --no-git-tag-version
        else
          npm version $TAG_NAME --no-git-tag-version
        fi

    - name: Commit and push version update
      run: |
        git config --local user.name "${{secrets.GH_USERNAME}}"
        git config --local user.email "${{secrets.GH_EMAIL}}"
        git remote set-url origin https://${{secrets.PUBLISH_GITHUB_TOKEN}}@github.com/${{github.repository}}
        git add package.json
        git commit -m "chore(release): update package version to ${{ steps.update_version.outputs.new_version }}"
        git push origin HEAD:master

    - name: Trigger Workflow B
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PUBLISH_GITHUB_TOKEN }}" \
          https://api.github.com/repos/slxca/mockr.js/actions/workflows/npm-publish.yml/dispatches \
          -d '{"ref":"master"}'
